global:
  scrape_interval: 15s # scrape interval to every 15 seconds.
  evaluation_interval: 15s # evaluate rules every 15 seconds.

scrape_configs:
  - job_name: "prometheus"
    # metrics_path defaults to '/metrics'
    static_configs:
      - targets: ["prometheus:9090"]
  - job_name: "cadvisor"
    scrape_interval: 5s
    static_configs:
      - targets: ["cadvisor:8080"]
